// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feedback_collector.proto

package com.example.feedback;

public final class FeedbackCollectorProto {
  private FeedbackCollectorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FeedbackRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:feedback.FeedbackRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string feedback_text = 1;</code>
     * @return The feedbackText.
     */
    java.lang.String getFeedbackText();
    /**
     * <code>string feedback_text = 1;</code>
     * @return The bytes for feedbackText.
     */
    com.google.protobuf.ByteString
        getFeedbackTextBytes();
  }
  /**
   * Protobuf type {@code feedback.FeedbackRequest}
   */
  public static final class FeedbackRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:feedback.FeedbackRequest)
      FeedbackRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FeedbackRequest.newBuilder() to construct.
    private FeedbackRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeedbackRequest() {
      feedbackText_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FeedbackRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FeedbackRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              feedbackText_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.feedback.FeedbackCollectorProto.FeedbackRequest.class, com.example.feedback.FeedbackCollectorProto.FeedbackRequest.Builder.class);
    }

    public static final int FEEDBACK_TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object feedbackText_;
    /**
     * <code>string feedback_text = 1;</code>
     * @return The feedbackText.
     */
    @java.lang.Override
    public java.lang.String getFeedbackText() {
      java.lang.Object ref = feedbackText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        feedbackText_ = s;
        return s;
      }
    }
    /**
     * <code>string feedback_text = 1;</code>
     * @return The bytes for feedbackText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFeedbackTextBytes() {
      java.lang.Object ref = feedbackText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feedbackText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(feedbackText_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, feedbackText_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(feedbackText_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, feedbackText_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.feedback.FeedbackCollectorProto.FeedbackRequest)) {
        return super.equals(obj);
      }
      com.example.feedback.FeedbackCollectorProto.FeedbackRequest other = (com.example.feedback.FeedbackCollectorProto.FeedbackRequest) obj;

      if (!getFeedbackText()
          .equals(other.getFeedbackText())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FEEDBACK_TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getFeedbackText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.feedback.FeedbackCollectorProto.FeedbackRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code feedback.FeedbackRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:feedback.FeedbackRequest)
        com.example.feedback.FeedbackCollectorProto.FeedbackRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.feedback.FeedbackCollectorProto.FeedbackRequest.class, com.example.feedback.FeedbackCollectorProto.FeedbackRequest.Builder.class);
      }

      // Construct using com.example.feedback.FeedbackCollectorProto.FeedbackRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        feedbackText_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackRequest_descriptor;
      }

      @java.lang.Override
      public com.example.feedback.FeedbackCollectorProto.FeedbackRequest getDefaultInstanceForType() {
        return com.example.feedback.FeedbackCollectorProto.FeedbackRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.feedback.FeedbackCollectorProto.FeedbackRequest build() {
        com.example.feedback.FeedbackCollectorProto.FeedbackRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.feedback.FeedbackCollectorProto.FeedbackRequest buildPartial() {
        com.example.feedback.FeedbackCollectorProto.FeedbackRequest result = new com.example.feedback.FeedbackCollectorProto.FeedbackRequest(this);
        result.feedbackText_ = feedbackText_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.feedback.FeedbackCollectorProto.FeedbackRequest) {
          return mergeFrom((com.example.feedback.FeedbackCollectorProto.FeedbackRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.feedback.FeedbackCollectorProto.FeedbackRequest other) {
        if (other == com.example.feedback.FeedbackCollectorProto.FeedbackRequest.getDefaultInstance()) return this;
        if (!other.getFeedbackText().isEmpty()) {
          feedbackText_ = other.feedbackText_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.feedback.FeedbackCollectorProto.FeedbackRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.feedback.FeedbackCollectorProto.FeedbackRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object feedbackText_ = "";
      /**
       * <code>string feedback_text = 1;</code>
       * @return The feedbackText.
       */
      public java.lang.String getFeedbackText() {
        java.lang.Object ref = feedbackText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          feedbackText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string feedback_text = 1;</code>
       * @return The bytes for feedbackText.
       */
      public com.google.protobuf.ByteString
          getFeedbackTextBytes() {
        java.lang.Object ref = feedbackText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          feedbackText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string feedback_text = 1;</code>
       * @param value The feedbackText to set.
       * @return This builder for chaining.
       */
      public Builder setFeedbackText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        feedbackText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string feedback_text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeedbackText() {
        
        feedbackText_ = getDefaultInstance().getFeedbackText();
        onChanged();
        return this;
      }
      /**
       * <code>string feedback_text = 1;</code>
       * @param value The bytes for feedbackText to set.
       * @return This builder for chaining.
       */
      public Builder setFeedbackTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        feedbackText_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:feedback.FeedbackRequest)
    }

    // @@protoc_insertion_point(class_scope:feedback.FeedbackRequest)
    private static final com.example.feedback.FeedbackCollectorProto.FeedbackRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.feedback.FeedbackCollectorProto.FeedbackRequest();
    }

    public static com.example.feedback.FeedbackCollectorProto.FeedbackRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeedbackRequest>
        PARSER = new com.google.protobuf.AbstractParser<FeedbackRequest>() {
      @java.lang.Override
      public FeedbackRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedbackRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FeedbackRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeedbackRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.feedback.FeedbackCollectorProto.FeedbackRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FeedbackSummaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:feedback.FeedbackSummary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 total_feedbacks = 1;</code>
     * @return The totalFeedbacks.
     */
    int getTotalFeedbacks();

    /**
     * <code>float average_sentiment_score = 2;</code>
     * @return The averageSentimentScore.
     */
    float getAverageSentimentScore();

    /**
     * <code>int32 negative_count = 3;</code>
     * @return The negativeCount.
     */
    int getNegativeCount();

    /**
     * <code>int32 positive_count = 4;</code>
     * @return The positiveCount.
     */
    int getPositiveCount();
  }
  /**
   * Protobuf type {@code feedback.FeedbackSummary}
   */
  public static final class FeedbackSummary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:feedback.FeedbackSummary)
      FeedbackSummaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FeedbackSummary.newBuilder() to construct.
    private FeedbackSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeedbackSummary() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FeedbackSummary();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FeedbackSummary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              totalFeedbacks_ = input.readInt32();
              break;
            }
            case 21: {

              averageSentimentScore_ = input.readFloat();
              break;
            }
            case 24: {

              negativeCount_ = input.readInt32();
              break;
            }
            case 32: {

              positiveCount_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.feedback.FeedbackCollectorProto.FeedbackSummary.class, com.example.feedback.FeedbackCollectorProto.FeedbackSummary.Builder.class);
    }

    public static final int TOTAL_FEEDBACKS_FIELD_NUMBER = 1;
    private int totalFeedbacks_;
    /**
     * <code>int32 total_feedbacks = 1;</code>
     * @return The totalFeedbacks.
     */
    @java.lang.Override
    public int getTotalFeedbacks() {
      return totalFeedbacks_;
    }

    public static final int AVERAGE_SENTIMENT_SCORE_FIELD_NUMBER = 2;
    private float averageSentimentScore_;
    /**
     * <code>float average_sentiment_score = 2;</code>
     * @return The averageSentimentScore.
     */
    @java.lang.Override
    public float getAverageSentimentScore() {
      return averageSentimentScore_;
    }

    public static final int NEGATIVE_COUNT_FIELD_NUMBER = 3;
    private int negativeCount_;
    /**
     * <code>int32 negative_count = 3;</code>
     * @return The negativeCount.
     */
    @java.lang.Override
    public int getNegativeCount() {
      return negativeCount_;
    }

    public static final int POSITIVE_COUNT_FIELD_NUMBER = 4;
    private int positiveCount_;
    /**
     * <code>int32 positive_count = 4;</code>
     * @return The positiveCount.
     */
    @java.lang.Override
    public int getPositiveCount() {
      return positiveCount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (totalFeedbacks_ != 0) {
        output.writeInt32(1, totalFeedbacks_);
      }
      if (java.lang.Float.floatToRawIntBits(averageSentimentScore_) != 0) {
        output.writeFloat(2, averageSentimentScore_);
      }
      if (negativeCount_ != 0) {
        output.writeInt32(3, negativeCount_);
      }
      if (positiveCount_ != 0) {
        output.writeInt32(4, positiveCount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (totalFeedbacks_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, totalFeedbacks_);
      }
      if (java.lang.Float.floatToRawIntBits(averageSentimentScore_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, averageSentimentScore_);
      }
      if (negativeCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, negativeCount_);
      }
      if (positiveCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, positiveCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.feedback.FeedbackCollectorProto.FeedbackSummary)) {
        return super.equals(obj);
      }
      com.example.feedback.FeedbackCollectorProto.FeedbackSummary other = (com.example.feedback.FeedbackCollectorProto.FeedbackSummary) obj;

      if (getTotalFeedbacks()
          != other.getTotalFeedbacks()) return false;
      if (java.lang.Float.floatToIntBits(getAverageSentimentScore())
          != java.lang.Float.floatToIntBits(
              other.getAverageSentimentScore())) return false;
      if (getNegativeCount()
          != other.getNegativeCount()) return false;
      if (getPositiveCount()
          != other.getPositiveCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOTAL_FEEDBACKS_FIELD_NUMBER;
      hash = (53 * hash) + getTotalFeedbacks();
      hash = (37 * hash) + AVERAGE_SENTIMENT_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAverageSentimentScore());
      hash = (37 * hash) + NEGATIVE_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getNegativeCount();
      hash = (37 * hash) + POSITIVE_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getPositiveCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.feedback.FeedbackCollectorProto.FeedbackSummary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code feedback.FeedbackSummary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:feedback.FeedbackSummary)
        com.example.feedback.FeedbackCollectorProto.FeedbackSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackSummary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackSummary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.feedback.FeedbackCollectorProto.FeedbackSummary.class, com.example.feedback.FeedbackCollectorProto.FeedbackSummary.Builder.class);
      }

      // Construct using com.example.feedback.FeedbackCollectorProto.FeedbackSummary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        totalFeedbacks_ = 0;

        averageSentimentScore_ = 0F;

        negativeCount_ = 0;

        positiveCount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.feedback.FeedbackCollectorProto.internal_static_feedback_FeedbackSummary_descriptor;
      }

      @java.lang.Override
      public com.example.feedback.FeedbackCollectorProto.FeedbackSummary getDefaultInstanceForType() {
        return com.example.feedback.FeedbackCollectorProto.FeedbackSummary.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.feedback.FeedbackCollectorProto.FeedbackSummary build() {
        com.example.feedback.FeedbackCollectorProto.FeedbackSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.feedback.FeedbackCollectorProto.FeedbackSummary buildPartial() {
        com.example.feedback.FeedbackCollectorProto.FeedbackSummary result = new com.example.feedback.FeedbackCollectorProto.FeedbackSummary(this);
        result.totalFeedbacks_ = totalFeedbacks_;
        result.averageSentimentScore_ = averageSentimentScore_;
        result.negativeCount_ = negativeCount_;
        result.positiveCount_ = positiveCount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.feedback.FeedbackCollectorProto.FeedbackSummary) {
          return mergeFrom((com.example.feedback.FeedbackCollectorProto.FeedbackSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.feedback.FeedbackCollectorProto.FeedbackSummary other) {
        if (other == com.example.feedback.FeedbackCollectorProto.FeedbackSummary.getDefaultInstance()) return this;
        if (other.getTotalFeedbacks() != 0) {
          setTotalFeedbacks(other.getTotalFeedbacks());
        }
        if (other.getAverageSentimentScore() != 0F) {
          setAverageSentimentScore(other.getAverageSentimentScore());
        }
        if (other.getNegativeCount() != 0) {
          setNegativeCount(other.getNegativeCount());
        }
        if (other.getPositiveCount() != 0) {
          setPositiveCount(other.getPositiveCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.feedback.FeedbackCollectorProto.FeedbackSummary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.feedback.FeedbackCollectorProto.FeedbackSummary) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int totalFeedbacks_ ;
      /**
       * <code>int32 total_feedbacks = 1;</code>
       * @return The totalFeedbacks.
       */
      @java.lang.Override
      public int getTotalFeedbacks() {
        return totalFeedbacks_;
      }
      /**
       * <code>int32 total_feedbacks = 1;</code>
       * @param value The totalFeedbacks to set.
       * @return This builder for chaining.
       */
      public Builder setTotalFeedbacks(int value) {
        
        totalFeedbacks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total_feedbacks = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalFeedbacks() {
        
        totalFeedbacks_ = 0;
        onChanged();
        return this;
      }

      private float averageSentimentScore_ ;
      /**
       * <code>float average_sentiment_score = 2;</code>
       * @return The averageSentimentScore.
       */
      @java.lang.Override
      public float getAverageSentimentScore() {
        return averageSentimentScore_;
      }
      /**
       * <code>float average_sentiment_score = 2;</code>
       * @param value The averageSentimentScore to set.
       * @return This builder for chaining.
       */
      public Builder setAverageSentimentScore(float value) {
        
        averageSentimentScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float average_sentiment_score = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAverageSentimentScore() {
        
        averageSentimentScore_ = 0F;
        onChanged();
        return this;
      }

      private int negativeCount_ ;
      /**
       * <code>int32 negative_count = 3;</code>
       * @return The negativeCount.
       */
      @java.lang.Override
      public int getNegativeCount() {
        return negativeCount_;
      }
      /**
       * <code>int32 negative_count = 3;</code>
       * @param value The negativeCount to set.
       * @return This builder for chaining.
       */
      public Builder setNegativeCount(int value) {
        
        negativeCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 negative_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNegativeCount() {
        
        negativeCount_ = 0;
        onChanged();
        return this;
      }

      private int positiveCount_ ;
      /**
       * <code>int32 positive_count = 4;</code>
       * @return The positiveCount.
       */
      @java.lang.Override
      public int getPositiveCount() {
        return positiveCount_;
      }
      /**
       * <code>int32 positive_count = 4;</code>
       * @param value The positiveCount to set.
       * @return This builder for chaining.
       */
      public Builder setPositiveCount(int value) {
        
        positiveCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 positive_count = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPositiveCount() {
        
        positiveCount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:feedback.FeedbackSummary)
    }

    // @@protoc_insertion_point(class_scope:feedback.FeedbackSummary)
    private static final com.example.feedback.FeedbackCollectorProto.FeedbackSummary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.feedback.FeedbackCollectorProto.FeedbackSummary();
    }

    public static com.example.feedback.FeedbackCollectorProto.FeedbackSummary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeedbackSummary>
        PARSER = new com.google.protobuf.AbstractParser<FeedbackSummary>() {
      @java.lang.Override
      public FeedbackSummary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedbackSummary(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FeedbackSummary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeedbackSummary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.feedback.FeedbackCollectorProto.FeedbackSummary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedback_FeedbackRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedback_FeedbackRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedback_FeedbackSummary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedback_FeedbackSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030feedback_collector.proto\022\010feedback\"(\n\017" +
      "FeedbackRequest\022\025\n\rfeedback_text\030\001 \001(\t\"{" +
      "\n\017FeedbackSummary\022\027\n\017total_feedbacks\030\001 \001" +
      "(\005\022\037\n\027average_sentiment_score\030\002 \001(\002\022\026\n\016n" +
      "egative_count\030\003 \001(\005\022\026\n\016positive_count\030\004 " +
      "\001(\0052e\n\030FeedbackCollectorService\022I\n\017Submi" +
      "tFeedbacks\022\031.feedback.FeedbackRequest\032\031." +
      "feedback.FeedbackSummary(\001B.\n\024com.exampl" +
      "e.feedbackB\026FeedbackCollectorProtob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_feedback_FeedbackRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_feedback_FeedbackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedback_FeedbackRequest_descriptor,
        new java.lang.String[] { "FeedbackText", });
    internal_static_feedback_FeedbackSummary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_feedback_FeedbackSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedback_FeedbackSummary_descriptor,
        new java.lang.String[] { "TotalFeedbacks", "AverageSentimentScore", "NegativeCount", "PositiveCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
