// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert_service.proto

package com.example.alert;

public final class AlertServiceProto {
  private AlertServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AlertRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:alert.AlertRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ticket_id = 1;</code>
     * @return The ticketId.
     */
    java.lang.String getTicketId();
    /**
     * <code>string ticket_id = 1;</code>
     * @return The bytes for ticketId.
     */
    com.google.protobuf.ByteString
        getTicketIdBytes();

    /**
     * <pre>
     * e.g., "critical", "medium", "low"
     * </pre>
     *
     * <code>string urgency = 2;</code>
     * @return The urgency.
     */
    java.lang.String getUrgency();
    /**
     * <pre>
     * e.g., "critical", "medium", "low"
     * </pre>
     *
     * <code>string urgency = 2;</code>
     * @return The bytes for urgency.
     */
    com.google.protobuf.ByteString
        getUrgencyBytes();

    /**
     * <code>string sentiment = 3;</code>
     * @return The sentiment.
     */
    java.lang.String getSentiment();
    /**
     * <code>string sentiment = 3;</code>
     * @return The bytes for sentiment.
     */
    com.google.protobuf.ByteString
        getSentimentBytes();

    /**
     * <code>string message = 4;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 4;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code alert.AlertRequest}
   */
  public static final class AlertRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:alert.AlertRequest)
      AlertRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlertRequest.newBuilder() to construct.
    private AlertRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlertRequest() {
      ticketId_ = "";
      urgency_ = "";
      sentiment_ = "";
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AlertRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AlertRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ticketId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              urgency_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sentiment_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.alert.AlertServiceProto.internal_static_alert_AlertRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.alert.AlertServiceProto.internal_static_alert_AlertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.alert.AlertServiceProto.AlertRequest.class, com.example.alert.AlertServiceProto.AlertRequest.Builder.class);
    }

    public static final int TICKET_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object ticketId_;
    /**
     * <code>string ticket_id = 1;</code>
     * @return The ticketId.
     */
    @java.lang.Override
    public java.lang.String getTicketId() {
      java.lang.Object ref = ticketId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ticketId_ = s;
        return s;
      }
    }
    /**
     * <code>string ticket_id = 1;</code>
     * @return The bytes for ticketId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTicketIdBytes() {
      java.lang.Object ref = ticketId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticketId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URGENCY_FIELD_NUMBER = 2;
    private volatile java.lang.Object urgency_;
    /**
     * <pre>
     * e.g., "critical", "medium", "low"
     * </pre>
     *
     * <code>string urgency = 2;</code>
     * @return The urgency.
     */
    @java.lang.Override
    public java.lang.String getUrgency() {
      java.lang.Object ref = urgency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        urgency_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * e.g., "critical", "medium", "low"
     * </pre>
     *
     * <code>string urgency = 2;</code>
     * @return The bytes for urgency.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrgencyBytes() {
      java.lang.Object ref = urgency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        urgency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENTIMENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object sentiment_;
    /**
     * <code>string sentiment = 3;</code>
     * @return The sentiment.
     */
    @java.lang.Override
    public java.lang.String getSentiment() {
      java.lang.Object ref = sentiment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sentiment_ = s;
        return s;
      }
    }
    /**
     * <code>string sentiment = 3;</code>
     * @return The bytes for sentiment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSentimentBytes() {
      java.lang.Object ref = sentiment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sentiment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 4;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 4;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ticketId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ticketId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(urgency_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, urgency_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sentiment_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sentiment_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ticketId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ticketId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(urgency_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, urgency_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sentiment_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sentiment_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.alert.AlertServiceProto.AlertRequest)) {
        return super.equals(obj);
      }
      com.example.alert.AlertServiceProto.AlertRequest other = (com.example.alert.AlertServiceProto.AlertRequest) obj;

      if (!getTicketId()
          .equals(other.getTicketId())) return false;
      if (!getUrgency()
          .equals(other.getUrgency())) return false;
      if (!getSentiment()
          .equals(other.getSentiment())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TICKET_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTicketId().hashCode();
      hash = (37 * hash) + URGENCY_FIELD_NUMBER;
      hash = (53 * hash) + getUrgency().hashCode();
      hash = (37 * hash) + SENTIMENT_FIELD_NUMBER;
      hash = (53 * hash) + getSentiment().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.alert.AlertServiceProto.AlertRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.alert.AlertServiceProto.AlertRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code alert.AlertRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:alert.AlertRequest)
        com.example.alert.AlertServiceProto.AlertRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.alert.AlertServiceProto.internal_static_alert_AlertRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.alert.AlertServiceProto.internal_static_alert_AlertRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.alert.AlertServiceProto.AlertRequest.class, com.example.alert.AlertServiceProto.AlertRequest.Builder.class);
      }

      // Construct using com.example.alert.AlertServiceProto.AlertRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ticketId_ = "";

        urgency_ = "";

        sentiment_ = "";

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.alert.AlertServiceProto.internal_static_alert_AlertRequest_descriptor;
      }

      @java.lang.Override
      public com.example.alert.AlertServiceProto.AlertRequest getDefaultInstanceForType() {
        return com.example.alert.AlertServiceProto.AlertRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.alert.AlertServiceProto.AlertRequest build() {
        com.example.alert.AlertServiceProto.AlertRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.alert.AlertServiceProto.AlertRequest buildPartial() {
        com.example.alert.AlertServiceProto.AlertRequest result = new com.example.alert.AlertServiceProto.AlertRequest(this);
        result.ticketId_ = ticketId_;
        result.urgency_ = urgency_;
        result.sentiment_ = sentiment_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.alert.AlertServiceProto.AlertRequest) {
          return mergeFrom((com.example.alert.AlertServiceProto.AlertRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.alert.AlertServiceProto.AlertRequest other) {
        if (other == com.example.alert.AlertServiceProto.AlertRequest.getDefaultInstance()) return this;
        if (!other.getTicketId().isEmpty()) {
          ticketId_ = other.ticketId_;
          onChanged();
        }
        if (!other.getUrgency().isEmpty()) {
          urgency_ = other.urgency_;
          onChanged();
        }
        if (!other.getSentiment().isEmpty()) {
          sentiment_ = other.sentiment_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.alert.AlertServiceProto.AlertRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.alert.AlertServiceProto.AlertRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ticketId_ = "";
      /**
       * <code>string ticket_id = 1;</code>
       * @return The ticketId.
       */
      public java.lang.String getTicketId() {
        java.lang.Object ref = ticketId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ticketId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ticket_id = 1;</code>
       * @return The bytes for ticketId.
       */
      public com.google.protobuf.ByteString
          getTicketIdBytes() {
        java.lang.Object ref = ticketId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ticketId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ticket_id = 1;</code>
       * @param value The ticketId to set.
       * @return This builder for chaining.
       */
      public Builder setTicketId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ticketId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ticket_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTicketId() {
        
        ticketId_ = getDefaultInstance().getTicketId();
        onChanged();
        return this;
      }
      /**
       * <code>string ticket_id = 1;</code>
       * @param value The bytes for ticketId to set.
       * @return This builder for chaining.
       */
      public Builder setTicketIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ticketId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object urgency_ = "";
      /**
       * <pre>
       * e.g., "critical", "medium", "low"
       * </pre>
       *
       * <code>string urgency = 2;</code>
       * @return The urgency.
       */
      public java.lang.String getUrgency() {
        java.lang.Object ref = urgency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          urgency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * e.g., "critical", "medium", "low"
       * </pre>
       *
       * <code>string urgency = 2;</code>
       * @return The bytes for urgency.
       */
      public com.google.protobuf.ByteString
          getUrgencyBytes() {
        java.lang.Object ref = urgency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          urgency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * e.g., "critical", "medium", "low"
       * </pre>
       *
       * <code>string urgency = 2;</code>
       * @param value The urgency to set.
       * @return This builder for chaining.
       */
      public Builder setUrgency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        urgency_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g., "critical", "medium", "low"
       * </pre>
       *
       * <code>string urgency = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrgency() {
        
        urgency_ = getDefaultInstance().getUrgency();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g., "critical", "medium", "low"
       * </pre>
       *
       * <code>string urgency = 2;</code>
       * @param value The bytes for urgency to set.
       * @return This builder for chaining.
       */
      public Builder setUrgencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        urgency_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sentiment_ = "";
      /**
       * <code>string sentiment = 3;</code>
       * @return The sentiment.
       */
      public java.lang.String getSentiment() {
        java.lang.Object ref = sentiment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sentiment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sentiment = 3;</code>
       * @return The bytes for sentiment.
       */
      public com.google.protobuf.ByteString
          getSentimentBytes() {
        java.lang.Object ref = sentiment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sentiment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sentiment = 3;</code>
       * @param value The sentiment to set.
       * @return This builder for chaining.
       */
      public Builder setSentiment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sentiment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sentiment = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSentiment() {
        
        sentiment_ = getDefaultInstance().getSentiment();
        onChanged();
        return this;
      }
      /**
       * <code>string sentiment = 3;</code>
       * @param value The bytes for sentiment to set.
       * @return This builder for chaining.
       */
      public Builder setSentimentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sentiment_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 4;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 4;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 4;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 4;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:alert.AlertRequest)
    }

    // @@protoc_insertion_point(class_scope:alert.AlertRequest)
    private static final com.example.alert.AlertServiceProto.AlertRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.alert.AlertServiceProto.AlertRequest();
    }

    public static com.example.alert.AlertServiceProto.AlertRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlertRequest>
        PARSER = new com.google.protobuf.AbstractParser<AlertRequest>() {
      @java.lang.Override
      public AlertRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlertRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AlertRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlertRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.alert.AlertServiceProto.AlertRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AlertResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:alert.AlertResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * e.g., "sent", "failed"
     * </pre>
     *
     * <code>string status = 1;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <pre>
     * e.g., "sent", "failed"
     * </pre>
     *
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <pre>
     * e.g., ISO-8601 format
     * </pre>
     *
     * <code>string timestamp = 2;</code>
     * @return The timestamp.
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     * e.g., ISO-8601 format
     * </pre>
     *
     * <code>string timestamp = 2;</code>
     * @return The bytes for timestamp.
     */
    com.google.protobuf.ByteString
        getTimestampBytes();
  }
  /**
   * Protobuf type {@code alert.AlertResponse}
   */
  public static final class AlertResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:alert.AlertResponse)
      AlertResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlertResponse.newBuilder() to construct.
    private AlertResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlertResponse() {
      status_ = "";
      timestamp_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AlertResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AlertResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.alert.AlertServiceProto.internal_static_alert_AlertResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.alert.AlertServiceProto.internal_static_alert_AlertResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.alert.AlertServiceProto.AlertResponse.class, com.example.alert.AlertServiceProto.AlertResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private volatile java.lang.Object status_;
    /**
     * <pre>
     * e.g., "sent", "failed"
     * </pre>
     *
     * <code>string status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * e.g., "sent", "failed"
     * </pre>
     *
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     * e.g., ISO-8601 format
     * </pre>
     *
     * <code>string timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * e.g., ISO-8601 format
     * </pre>
     *
     * <code>string timestamp = 2;</code>
     * @return The bytes for timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.alert.AlertServiceProto.AlertResponse)) {
        return super.equals(obj);
      }
      com.example.alert.AlertServiceProto.AlertResponse other = (com.example.alert.AlertServiceProto.AlertResponse) obj;

      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.alert.AlertServiceProto.AlertResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.alert.AlertServiceProto.AlertResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code alert.AlertResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:alert.AlertResponse)
        com.example.alert.AlertServiceProto.AlertResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.alert.AlertServiceProto.internal_static_alert_AlertResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.alert.AlertServiceProto.internal_static_alert_AlertResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.alert.AlertServiceProto.AlertResponse.class, com.example.alert.AlertServiceProto.AlertResponse.Builder.class);
      }

      // Construct using com.example.alert.AlertServiceProto.AlertResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = "";

        timestamp_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.alert.AlertServiceProto.internal_static_alert_AlertResponse_descriptor;
      }

      @java.lang.Override
      public com.example.alert.AlertServiceProto.AlertResponse getDefaultInstanceForType() {
        return com.example.alert.AlertServiceProto.AlertResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.alert.AlertServiceProto.AlertResponse build() {
        com.example.alert.AlertServiceProto.AlertResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.alert.AlertServiceProto.AlertResponse buildPartial() {
        com.example.alert.AlertServiceProto.AlertResponse result = new com.example.alert.AlertServiceProto.AlertResponse(this);
        result.status_ = status_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.alert.AlertServiceProto.AlertResponse) {
          return mergeFrom((com.example.alert.AlertServiceProto.AlertResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.alert.AlertServiceProto.AlertResponse other) {
        if (other == com.example.alert.AlertServiceProto.AlertResponse.getDefaultInstance()) return this;
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.alert.AlertServiceProto.AlertResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.alert.AlertServiceProto.AlertResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <pre>
       * e.g., "sent", "failed"
       * </pre>
       *
       * <code>string status = 1;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * e.g., "sent", "failed"
       * </pre>
       *
       * <code>string status = 1;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * e.g., "sent", "failed"
       * </pre>
       *
       * <code>string status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g., "sent", "failed"
       * </pre>
       *
       * <code>string status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g., "sent", "failed"
       * </pre>
       *
       * <code>string status = 1;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       * e.g., ISO-8601 format
       * </pre>
       *
       * <code>string timestamp = 2;</code>
       * @return The timestamp.
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * e.g., ISO-8601 format
       * </pre>
       *
       * <code>string timestamp = 2;</code>
       * @return The bytes for timestamp.
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * e.g., ISO-8601 format
       * </pre>
       *
       * <code>string timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g., ISO-8601 format
       * </pre>
       *
       * <code>string timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g., ISO-8601 format
       * </pre>
       *
       * <code>string timestamp = 2;</code>
       * @param value The bytes for timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:alert.AlertResponse)
    }

    // @@protoc_insertion_point(class_scope:alert.AlertResponse)
    private static final com.example.alert.AlertServiceProto.AlertResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.alert.AlertServiceProto.AlertResponse();
    }

    public static com.example.alert.AlertServiceProto.AlertResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlertResponse>
        PARSER = new com.google.protobuf.AbstractParser<AlertResponse>() {
      @java.lang.Override
      public AlertResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlertResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AlertResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlertResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.alert.AlertServiceProto.AlertResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alert_AlertRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alert_AlertRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alert_AlertResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alert_AlertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023alert_service.proto\022\005alert\"V\n\014AlertReq" +
      "uest\022\021\n\tticket_id\030\001 \001(\t\022\017\n\007urgency\030\002 \001(\t" +
      "\022\021\n\tsentiment\030\003 \001(\t\022\017\n\007message\030\004 \001(\t\"2\n\r" +
      "AlertResponse\022\016\n\006status\030\001 \001(\t\022\021\n\ttimesta" +
      "mp\030\002 \001(\t2M\n\014AlertService\022=\n\014AlertChannel" +
      "\022\023.alert.AlertRequest\032\024.alert.AlertRespo" +
      "nse(\0010\001B&\n\021com.example.alertB\021AlertServi" +
      "ceProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_alert_AlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alert_AlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alert_AlertRequest_descriptor,
        new java.lang.String[] { "TicketId", "Urgency", "Sentiment", "Message", });
    internal_static_alert_AlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alert_AlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alert_AlertResponse_descriptor,
        new java.lang.String[] { "Status", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
