// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sentiment_analyzer.proto

package com.example.sentiment;

public final class SentimentAnalyzerProto {
  private SentimentAnalyzerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentiment.TextRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code sentiment.TextRequest}
   */
  public static final class TextRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentiment.TextRequest)
      TextRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextRequest.newBuilder() to construct.
    private TextRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextRequest() {
      text_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TextRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TextRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_TextRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_TextRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.sentiment.SentimentAnalyzerProto.TextRequest.class, com.example.sentiment.SentimentAnalyzerProto.TextRequest.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.sentiment.SentimentAnalyzerProto.TextRequest)) {
        return super.equals(obj);
      }
      com.example.sentiment.SentimentAnalyzerProto.TextRequest other = (com.example.sentiment.SentimentAnalyzerProto.TextRequest) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.sentiment.SentimentAnalyzerProto.TextRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentiment.TextRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentiment.TextRequest)
        com.example.sentiment.SentimentAnalyzerProto.TextRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_TextRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_TextRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.sentiment.SentimentAnalyzerProto.TextRequest.class, com.example.sentiment.SentimentAnalyzerProto.TextRequest.Builder.class);
      }

      // Construct using com.example.sentiment.SentimentAnalyzerProto.TextRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        text_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_TextRequest_descriptor;
      }

      @java.lang.Override
      public com.example.sentiment.SentimentAnalyzerProto.TextRequest getDefaultInstanceForType() {
        return com.example.sentiment.SentimentAnalyzerProto.TextRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.sentiment.SentimentAnalyzerProto.TextRequest build() {
        com.example.sentiment.SentimentAnalyzerProto.TextRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.sentiment.SentimentAnalyzerProto.TextRequest buildPartial() {
        com.example.sentiment.SentimentAnalyzerProto.TextRequest result = new com.example.sentiment.SentimentAnalyzerProto.TextRequest(this);
        result.text_ = text_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.sentiment.SentimentAnalyzerProto.TextRequest) {
          return mergeFrom((com.example.sentiment.SentimentAnalyzerProto.TextRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.sentiment.SentimentAnalyzerProto.TextRequest other) {
        if (other == com.example.sentiment.SentimentAnalyzerProto.TextRequest.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.sentiment.SentimentAnalyzerProto.TextRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.sentiment.SentimentAnalyzerProto.TextRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentiment.TextRequest)
    }

    // @@protoc_insertion_point(class_scope:sentiment.TextRequest)
    private static final com.example.sentiment.SentimentAnalyzerProto.TextRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.sentiment.SentimentAnalyzerProto.TextRequest();
    }

    public static com.example.sentiment.SentimentAnalyzerProto.TextRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextRequest>
        PARSER = new com.google.protobuf.AbstractParser<TextRequest>() {
      @java.lang.Override
      public TextRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.sentiment.SentimentAnalyzerProto.TextRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SentimentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentiment.SentimentResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * e.g., "positive", "neutral", "negative"
     * </pre>
     *
     * <code>string sentiment = 1;</code>
     * @return The sentiment.
     */
    java.lang.String getSentiment();
    /**
     * <pre>
     * e.g., "positive", "neutral", "negative"
     * </pre>
     *
     * <code>string sentiment = 1;</code>
     * @return The bytes for sentiment.
     */
    com.google.protobuf.ByteString
        getSentimentBytes();

    /**
     * <pre>
     * Confidence score
     * </pre>
     *
     * <code>float score = 2;</code>
     * @return The score.
     */
    float getScore();

    /**
     * <pre>
     * Optional: to link to an alert
     * </pre>
     *
     * <code>string ticket_id = 3;</code>
     * @return The ticketId.
     */
    java.lang.String getTicketId();
    /**
     * <pre>
     * Optional: to link to an alert
     * </pre>
     *
     * <code>string ticket_id = 3;</code>
     * @return The bytes for ticketId.
     */
    com.google.protobuf.ByteString
        getTicketIdBytes();
  }
  /**
   * Protobuf type {@code sentiment.SentimentResponse}
   */
  public static final class SentimentResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentiment.SentimentResponse)
      SentimentResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SentimentResponse.newBuilder() to construct.
    private SentimentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SentimentResponse() {
      sentiment_ = "";
      ticketId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SentimentResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SentimentResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sentiment_ = s;
              break;
            }
            case 21: {

              score_ = input.readFloat();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ticketId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_SentimentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_SentimentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.sentiment.SentimentAnalyzerProto.SentimentResponse.class, com.example.sentiment.SentimentAnalyzerProto.SentimentResponse.Builder.class);
    }

    public static final int SENTIMENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object sentiment_;
    /**
     * <pre>
     * e.g., "positive", "neutral", "negative"
     * </pre>
     *
     * <code>string sentiment = 1;</code>
     * @return The sentiment.
     */
    @java.lang.Override
    public java.lang.String getSentiment() {
      java.lang.Object ref = sentiment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sentiment_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * e.g., "positive", "neutral", "negative"
     * </pre>
     *
     * <code>string sentiment = 1;</code>
     * @return The bytes for sentiment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSentimentBytes() {
      java.lang.Object ref = sentiment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sentiment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private float score_;
    /**
     * <pre>
     * Confidence score
     * </pre>
     *
     * <code>float score = 2;</code>
     * @return The score.
     */
    @java.lang.Override
    public float getScore() {
      return score_;
    }

    public static final int TICKET_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object ticketId_;
    /**
     * <pre>
     * Optional: to link to an alert
     * </pre>
     *
     * <code>string ticket_id = 3;</code>
     * @return The ticketId.
     */
    @java.lang.Override
    public java.lang.String getTicketId() {
      java.lang.Object ref = ticketId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ticketId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional: to link to an alert
     * </pre>
     *
     * <code>string ticket_id = 3;</code>
     * @return The bytes for ticketId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTicketIdBytes() {
      java.lang.Object ref = ticketId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticketId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sentiment_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sentiment_);
      }
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        output.writeFloat(2, score_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ticketId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ticketId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sentiment_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sentiment_);
      }
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, score_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ticketId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ticketId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.sentiment.SentimentAnalyzerProto.SentimentResponse)) {
        return super.equals(obj);
      }
      com.example.sentiment.SentimentAnalyzerProto.SentimentResponse other = (com.example.sentiment.SentimentAnalyzerProto.SentimentResponse) obj;

      if (!getSentiment()
          .equals(other.getSentiment())) return false;
      if (java.lang.Float.floatToIntBits(getScore())
          != java.lang.Float.floatToIntBits(
              other.getScore())) return false;
      if (!getTicketId()
          .equals(other.getTicketId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENTIMENT_FIELD_NUMBER;
      hash = (53 * hash) + getSentiment().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore());
      hash = (37 * hash) + TICKET_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTicketId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.sentiment.SentimentAnalyzerProto.SentimentResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentiment.SentimentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentiment.SentimentResponse)
        com.example.sentiment.SentimentAnalyzerProto.SentimentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_SentimentResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_SentimentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.sentiment.SentimentAnalyzerProto.SentimentResponse.class, com.example.sentiment.SentimentAnalyzerProto.SentimentResponse.Builder.class);
      }

      // Construct using com.example.sentiment.SentimentAnalyzerProto.SentimentResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sentiment_ = "";

        score_ = 0F;

        ticketId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.sentiment.SentimentAnalyzerProto.internal_static_sentiment_SentimentResponse_descriptor;
      }

      @java.lang.Override
      public com.example.sentiment.SentimentAnalyzerProto.SentimentResponse getDefaultInstanceForType() {
        return com.example.sentiment.SentimentAnalyzerProto.SentimentResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.sentiment.SentimentAnalyzerProto.SentimentResponse build() {
        com.example.sentiment.SentimentAnalyzerProto.SentimentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.sentiment.SentimentAnalyzerProto.SentimentResponse buildPartial() {
        com.example.sentiment.SentimentAnalyzerProto.SentimentResponse result = new com.example.sentiment.SentimentAnalyzerProto.SentimentResponse(this);
        result.sentiment_ = sentiment_;
        result.score_ = score_;
        result.ticketId_ = ticketId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.sentiment.SentimentAnalyzerProto.SentimentResponse) {
          return mergeFrom((com.example.sentiment.SentimentAnalyzerProto.SentimentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.sentiment.SentimentAnalyzerProto.SentimentResponse other) {
        if (other == com.example.sentiment.SentimentAnalyzerProto.SentimentResponse.getDefaultInstance()) return this;
        if (!other.getSentiment().isEmpty()) {
          sentiment_ = other.sentiment_;
          onChanged();
        }
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        if (!other.getTicketId().isEmpty()) {
          ticketId_ = other.ticketId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.sentiment.SentimentAnalyzerProto.SentimentResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.sentiment.SentimentAnalyzerProto.SentimentResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sentiment_ = "";
      /**
       * <pre>
       * e.g., "positive", "neutral", "negative"
       * </pre>
       *
       * <code>string sentiment = 1;</code>
       * @return The sentiment.
       */
      public java.lang.String getSentiment() {
        java.lang.Object ref = sentiment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sentiment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * e.g., "positive", "neutral", "negative"
       * </pre>
       *
       * <code>string sentiment = 1;</code>
       * @return The bytes for sentiment.
       */
      public com.google.protobuf.ByteString
          getSentimentBytes() {
        java.lang.Object ref = sentiment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sentiment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * e.g., "positive", "neutral", "negative"
       * </pre>
       *
       * <code>string sentiment = 1;</code>
       * @param value The sentiment to set.
       * @return This builder for chaining.
       */
      public Builder setSentiment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sentiment_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g., "positive", "neutral", "negative"
       * </pre>
       *
       * <code>string sentiment = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSentiment() {
        
        sentiment_ = getDefaultInstance().getSentiment();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g., "positive", "neutral", "negative"
       * </pre>
       *
       * <code>string sentiment = 1;</code>
       * @param value The bytes for sentiment to set.
       * @return This builder for chaining.
       */
      public Builder setSentimentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sentiment_ = value;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <pre>
       * Confidence score
       * </pre>
       *
       * <code>float score = 2;</code>
       * @return The score.
       */
      @java.lang.Override
      public float getScore() {
        return score_;
      }
      /**
       * <pre>
       * Confidence score
       * </pre>
       *
       * <code>float score = 2;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(float value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Confidence score
       * </pre>
       *
       * <code>float score = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object ticketId_ = "";
      /**
       * <pre>
       * Optional: to link to an alert
       * </pre>
       *
       * <code>string ticket_id = 3;</code>
       * @return The ticketId.
       */
      public java.lang.String getTicketId() {
        java.lang.Object ref = ticketId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ticketId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional: to link to an alert
       * </pre>
       *
       * <code>string ticket_id = 3;</code>
       * @return The bytes for ticketId.
       */
      public com.google.protobuf.ByteString
          getTicketIdBytes() {
        java.lang.Object ref = ticketId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ticketId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional: to link to an alert
       * </pre>
       *
       * <code>string ticket_id = 3;</code>
       * @param value The ticketId to set.
       * @return This builder for chaining.
       */
      public Builder setTicketId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ticketId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional: to link to an alert
       * </pre>
       *
       * <code>string ticket_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTicketId() {
        
        ticketId_ = getDefaultInstance().getTicketId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional: to link to an alert
       * </pre>
       *
       * <code>string ticket_id = 3;</code>
       * @param value The bytes for ticketId to set.
       * @return This builder for chaining.
       */
      public Builder setTicketIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ticketId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentiment.SentimentResponse)
    }

    // @@protoc_insertion_point(class_scope:sentiment.SentimentResponse)
    private static final com.example.sentiment.SentimentAnalyzerProto.SentimentResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.sentiment.SentimentAnalyzerProto.SentimentResponse();
    }

    public static com.example.sentiment.SentimentAnalyzerProto.SentimentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SentimentResponse>
        PARSER = new com.google.protobuf.AbstractParser<SentimentResponse>() {
      @java.lang.Override
      public SentimentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SentimentResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SentimentResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SentimentResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.sentiment.SentimentAnalyzerProto.SentimentResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentiment_TextRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentiment_TextRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentiment_SentimentResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentiment_SentimentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030sentiment_analyzer.proto\022\tsentiment\"\033\n" +
      "\013TextRequest\022\014\n\004text\030\001 \001(\t\"H\n\021SentimentR" +
      "esponse\022\021\n\tsentiment\030\001 \001(\t\022\r\n\005score\030\002 \001(" +
      "\002\022\021\n\tticket_id\030\003 \001(\t2\256\001\n\030SentimentAnalyz" +
      "erService\022C\n\013AnalyzeText\022\026.sentiment.Tex" +
      "tRequest\032\034.sentiment.SentimentResponse\022M" +
      "\n\023StreamLiveSentiment\022\026.sentiment.TextRe" +
      "quest\032\034.sentiment.SentimentResponse0\001B/\n" +
      "\025com.example.sentimentB\026SentimentAnalyze" +
      "rProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sentiment_TextRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sentiment_TextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentiment_TextRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_sentiment_SentimentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sentiment_SentimentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentiment_SentimentResponse_descriptor,
        new java.lang.String[] { "Sentiment", "Score", "TicketId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
